language: python
python:
  - 3.5
env:
  - NODE_VERSION=4
  - NODE_VERSION=node
before_script:
  - nvm install $NODE_VERSION
  - npm install
script:
  - npm run build
  - npm test
notifications:
  webhooks: http://webhook.hakatashi.com/travis
  email:
    on_success: change
    on_failure: change
